/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: abb1ca23c93eaab55368e1cfce759161)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	BUZZ_REQUIRE_AUTH: "1";
	BUZZ_REPLICATION_PEERS: "";
	BUZZ_REPLICATION_STREAMS: "";
	BUZZ_REPLICATION_READERS: "";
	BUZZ_OWNER_PUBKEY: "9c2fd8696a630bdf27c3d54394739bb3cbbf81b7cf7fa1e205a806eca33fa90e";
	BUZZ_NODE_LABEL: "cf-rendezvous";
	RELAY_NODES: DurableObjectNamespace<import("./index").RelayNode>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RelayNode";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
